LANG_TEXTS = {
    "tr": {
        "app_title": "Total Battle Paralı Asker Takas Botu",
        "control_panel_title": "Bot Kontrol Paneli",
        "status_ready": "Durum: Hazır",
        "status_running": "Durum: Bot Çalışıyor",
        "status_stopped": "Durum: Bot Durduruldu",
        "start_button": "Botu Başlat",
        "stop_button": "Botu Durdur",
        "settings_button": "Ayarlar",
        "log_title": "Olay Günlüğü",
        "dev_info": "Geliştiren: FATİH / HKL | Versiyon V1.10",
        "bot_start_log": "Paralı Asker Takas Botu görevi başlatıldı.",
        "folder_error": "Hata: Görsel klasörü '{}' bulunamadı. Lütfen doğru yolu ayarlayın.",
        "folder_error_popup": "Bot başlatılamadı. Görsel klasörü '{}' bulunamadı.",
        "tb_window_not_found": "Total Battle penceresi bulunamadı. Taramaya devam ediliyor...",
        "window_focus_error": "Pencere odaklanamadı: {}",
        "image_search_error": "Görsel aranırken hata oluştu ({}): {}",
        "image_clicked_log": "Görsel Tıklandı: {} @ {}",
        "image_not_found_log": "Takas görseli bulunamadı, tarama devam ediyor...",
        "bot_already_running_info": "Bot zaten çalışıyor.",
        "bot_stopped_log": "Paralı Asker Botu durduruldu.",
        "bot_already_stopped_info": "Bot zaten durdurulmuş durumda.",
        "warning_popup_tb_window_not_found": "Total Battle penceresi bulunamadı. Bot yine de çalışacak ancak doğru hedeflenemeyebilir.",
        "exit_confirm": "Uygulamayı kapatmak istediğinize emin misiniz? Bot durdurulacaktır.",
        "settings_window_title": "Bot Ayarları",
        "confidence_label": "Görsel Eşleşme Hassasiyeti (%):",
        "scan_time_label": "Tarama Bekleme Süresi (saniye):",
        "focus_checkbox": "Total Battle Penceresini Odakla (Tıklamadan Önce)",
        "sound_checkbox": "Sesli Bildirimleri Etkinleştir",
        "tb_window_name_label": "Total Battle Pencere Adı (Tam veya Kısmi):",
        "choose_image_folder_button": "Görsel Klasörü Seç",
        "image_folder_updated": "Görsel klasörü güncellendi: {}",
        "image_folder_cancelled": "Görsel klasörü seçimi iptal edildi.",
        "choose_sound_file_button": "Ses Dosyası Seç",
        "sound_file_updated": "Ses dosyası güncellendi: {}",
        "sound_file_cancelled": "Ses dosyası seçimi iptal edildi.",
        "save_settings_button": "Ayarları Kaydet",
        "settings_saved_log": "Ayarlar kaydedildi:",
        "setting_confidence": "  Hassasiyet: {:.0f}%",
        "setting_scan_time": "  Tarama Hızı: {:.1f} sn",
        "setting_window_focus": "  Pencere Odaklama: {}",
        "setting_sound_enabled": "  Sesli Bildirim: {}",
        "setting_tb_window_name": "  TB Pencere Adı: '{}'",
        "setting_image_folder": "  Görsel Klasörü: '{}'",
        "setting_sound_file": "  Ses Dosyası: '{}'",
        "setting_language": "  Seçilen Dil: '{}'",
        "sound_error": "Ses çalınamadı ({})",
        "sound_file_not_found": "Ses dosyası bulunamadı: {}",
        "language_select_label": "Dil Seçimi:",
        "language_updated": "Dil güncellendi: {}",
        "settings_not_saved_confirm": "Ayarlar kaydedilmedi. Yine de kapatmak istiyor musunuz?",
        "settings_not_saved_title": "Kaydedilmemiş Ayarlar",
        "total_clicks_label": "Toplam Tıklama",
        "not_found_images_label": "Bulunamayan Resim",
        "last_trade_time_label": "Son Takas Zamanı",
        "statistics_title": "İstatistikler"
    },
    "en": {
        "app_title": "Total Battle Mercenary Exchange Bot",
        "control_panel_title": "Bot Control Panel",
        "status_ready": "Status: Ready",
        "status_running": "Status: Bot Running",
        "status_stopped": "Status: Bot Stopped",
        "start_button": "Start Bot",
        "stop_button": "Stop Bot",
        "settings_button": "Settings",
        "log_title": "Event Log",
        "dev_info": "Developed by: FATİH / HKL | Version V1.10",
        "bot_start_log": "Mercenary Exchange Bot task started.",
        "folder_error": "Error: Image folder '{}' not found. Please set the correct path.",
        "folder_error_popup": "Bot could not be started. Image folder '{}' not found.",
        "tb_window_not_found": "Total Battle window not found. Continuing scan...",
        "window_focus_error": "Could not focus window: {}",
        "image_search_error": "Error searching for image ({}): {}",
        "image_clicked_log": "Image Clicked: {} @ {}",
        "image_not_found_log": "Mercenary image not found, continuing scan...",
        "bot_already_running_info": "Bot is already running.",
        "bot_stopped_log": "Mercenary Bot stopped.",
        "bot_already_stopped_info": "Bot is already stopped.",
        "warning_popup_tb_window_not_found": "Total Battle window not found. Bot will still run but may not target correctly.",
        "exit_confirm": "Are you sure you want to close the application? The bot will be stopped.",
        "settings_window_title": "Bot Settings",
        "confidence_label": "Image Match Confidence (%):",
        "scan_time_label": "Scan Wait Time (seconds):",
        "focus_checkbox": "Focus Total Battle Window (Before Click)",
        "sound_checkbox": "Enable Sound Notifications",
        "tb_window_name_label": "Total Battle Window Name (Full or Partial):",
        "choose_image_folder_button": "Choose Image Folder",
        "image_folder_updated": "Image folder updated: {}",
        "image_folder_cancelled": "Image folder selection cancelled.",
        "choose_sound_file_button": "Choose Sound File",
        "sound_file_updated": "Sound file updated: {}",
        "sound_file_cancelled": "Sound file selection cancelled.",
        "save_settings_button": "Save Settings",
        "settings_saved_log": "Settings saved:",
        "setting_confidence": "  Confidence: {:.0f}%",
        "setting_scan_time": "  Scan Speed: {:.1f} sec",
        "setting_window_focus": "  Window Focus: {}",
        "setting_sound_enabled": "  Sound Notifications: {}",
        "setting_tb_window_name": "  TB Window Name: '{}'",
        "setting_image_folder": "  Image Folder: '{}'",
        "setting_sound_file": "  Sound File: '{}'",
        "setting_language": "  Selected Language: '{}'",
        "settings_not_saved_confirm": "Settings not saved. Do you still want to close?",
        "settings_not_saved_title": "Unsaved Settings",
        "total_clicks_label": "Total Clicks",
        "not_found_images_label": "Not Found Images",
        "last_trade_time_label": "Last Trade Time",
        "statistics_title": "Statistics"
    },
    "es": {
        "app_title": "Bot de Intercambio de Mercenarios de Total Battle",
        "control_panel_title": "Panel de Control del Bot",
        "status_ready": "Estado: Listo",
        "status_running": "Estado: Bot en funcionamiento",
        "status_stopped": "Estado: Bot detenido",
        "start_button": "Iniciar Bot",
        "stop_button": "Detener Bot",
        "settings_button": "Configuración",
        "log_title": "Registro de Eventos",
        "dev_info": "Desarrollado por: FATİH / HKL | Versión V1.10",
        "bot_start_log": "Se ha iniciado la tarea del Bot de Intercambio de Mercenarios.",
        "folder_error": "Error: Carpeta de imágenes '{}' no encontrada. Por favor, configure la ruta correcta.",
        "folder_error_popup": "No se pudo iniciar el bot. Carpeta de imágenes '{}' no encontrada.",
        "tb_window_not_found": "Ventana de Total Battle no encontrada. Continuando con el escaneo...",
        "window_focus_error": "No se pudo enfocar la ventana: {}",
        "image_search_error": "Error al buscar imagen ({}): {}",
        "image_clicked_log": "Imagen clicada: {} @ {}",
        "image_not_found_log": "Imagen de intercambio no encontrada, escaneando...",
        "bot_already_running_info": "El bot ya está en funcionamiento.",
        "bot_stopped_log": "Bot de Mercenarios detenido.",
        "bot_already_stopped_info": "El bot ya está detenido.",
        "warning_popup_tb_window_not_found": "No se encontró la ventana de Total Battle. El bot seguirá funcionando, pero podría no apuntar correctamente.",
        "exit_confirm": "¿Está seguro de que desea cerrar la aplicación? El bot se detendrá.",
        "settings_window_title": "Configuración del Bot",
        "confidence_label": "Precisión de coincidencia de imagen (%):",
        "scan_time_label": "Tiempo de espera entre escaneos (segundos):",
        "focus_checkbox": "Enfocar ventana de Total Battle (antes de hacer clic)",
        "sound_checkbox": "Habilitar notificaciones de sonido",
        "tb_window_name_label": "Nombre de ventana de Total Battle (completo o parcial):",
        "choose_image_folder_button": "Seleccionar Carpeta de Imágenes",
        "image_folder_updated": "Carpeta de imágenes actualizada: {}",
        "image_folder_cancelled": "Selección de carpeta de imágenes cancelada.",
        "choose_sound_file_button": "Seleccionar Archivo de Sonido",
        "sound_file_updated": "Archivo de sonido actualizado: {}",
        "sound_file_cancelled": "Selección de archivo de sonido cancelada.",
        "save_settings_button": "Guardar Configuración",
        "settings_saved_log": "Configuración guardada:",
        "setting_confidence": "  Precisión: {:.0f}%",
        "setting_scan_time": "  Velocidad de escaneo: {:.1f} s",
        "setting_window_focus": "  Enfoque de ventana: {}",
        "setting_sound_enabled": "  Notificaciones de sonido: {}",
        "setting_tb_window_name": "  Nombre de ventana TB: '{}'",
        "setting_image_folder": "  Carpeta de imágenes: '{}'",
        "setting_sound_file": "  Archivo de sonido: '{}'",
        "setting_language": "  Idioma seleccionado: '{}'",
        "sound_error": "No se pudo reproducir el sonido ({})",
        "sound_file_not_found": "Archivo de sonido no encontrado: {}",
        "language_select_label": "Selección de idioma:",
        "language_updated": "Idioma actualizado: {}",
        "settings_not_saved_confirm": "Los ajustes no se han guardado. ¿Desea cerrar de todas formas?",
        "settings_not_saved_title": "Ajustes no guardados",
        "total_clicks_label": "Total de Clics",
        "not_found_images_label": "Imágenes No Encontradas",
        "last_trade_time_label": "Último Tiempo de Intercambio",
        "statistics_title": "Estadísticas"
    },
    "fr": {
        "app_title": "Bot d'Échange de Mercenaires pour Total Battle",
        "control_panel_title": "Panneau de Contrôle du Bot",
        "status_ready": "Statut : Prêt",
        "status_running": "Statut : Bot en cours d'exécution",
        "status_stopped": "Statut : Bot arrêté",
        "start_button": "Démarrer le Bot",
        "stop_button": "Arrêter le Bot",
        "settings_button": "Paramètres",
        "log_title": "Journal des Événements",
        "dev_info": "Développé par : FATİH / HKL | Version V1.10",
        "bot_start_log": "La tâche du Bot d'Échange de Mercenaires a été lancée.",
        "folder_error": "Erreur : Dossier d'images '{}' introuvable. Veuillez définir le chemin correct.",
        "folder_error_popup": "Impossible de démarrer le bot. Dossier d'images '{}' introuvable.",
        "tb_window_not_found": "Fenêtre Total Battle introuvable. Analyse en cours...",
        "window_focus_error": "Impossible de focaliser la fenêtre : {}",
        "image_search_error": "Erreur lors de la recherche d'image ({}): {}",
        "image_clicked_log": "Image cliquée : {} @ {}",
        "image_not_found_log": "Image d'échange introuvable, poursuite de l'analyse...",
        "bot_already_running_info": "Le bot est déjà en cours d'exécution.",
        "bot_stopped_log": "Bot de Mercenaires arrêté.",
        "bot_already_stopped_info": "Le bot est déjà arrêté.",
        "warning_popup_tb_window_not_found": "Fenêtre Total Battle introuvable. Le bot fonctionnera quand même mais pourrait ne pas viser correctement.",
        "exit_confirm": "Voulez-vous vraiment quitter l'application ? Le bot sera arrêté.",
        "settings_window_title": "Paramètres du Bot",
        "confidence_label": "Précision de la détection d'image (%):",
        "scan_time_label": "Délai entre les analyses (secondes) :",
        "focus_checkbox": "Focaliser la fenêtre Total Battle (avant clic)",
        "sound_checkbox": "Activer les notifications sonores",
        "tb_window_name_label": "Nom de la fenêtre Total Battle (partiel ou complet) :",
        "choose_image_folder_button": "Choisir le Dossier d'Images",
        "image_folder_updated": "Dossier d'images mis à jour : {}",
        "image_folder_cancelled": "Sélection du dossier d'images annulée.",
        "choose_sound_file_button": "Choisir un Fichier Son",
        "sound_file_updated": "Fichier son mis à jour : {}",
        "sound_file_cancelled": "Sélection de fichier son annulée.",
        "save_settings_button": "Enregistrer les Paramètres",
        "settings_saved_log": "Paramètres enregistrés :",
        "setting_confidence": "  Précision : {:.0f}%",
        "setting_scan_time": "  Vitesse d'analyse : {:.1f} s",
        "setting_window_focus": "  Focalisation de la fenêtre : {}",
        "setting_sound_enabled": "  Notification sonore : {}",
        "setting_tb_window_name": "  Nom de fenêtre TB : '{}'",
        "setting_image_folder": "  Dossier d'images : '{}'",
        "setting_sound_file": "  Fichier son : '{}'",
        "setting_language": "  Langue sélectionnée : '{}'",
        "sound_error": "Impossible de lire le son ({})",
        "sound_file_not_found": "Fichier son introuvable : {}",
        "language_select_label": "Sélection de la langue :",
        "language_updated": "Langue mise à jour : {}",
        "settings_not_saved_confirm": "Les paramètres n'ont pas été enregistrés. Voulez-vous vraiment quitter ?",
        "settings_not_saved_title": "Paramètres non enregistrés",
        "total_clicks_label": "Total de Clics",
        "not_found_images_label": "Images Introuvables",
        "last_trade_time_label": "Dernier Échange",
        "statistics_title": "Statistiques"
    },
    "de": {
        "app_title": "Total Battle Söldner-Tausch-Bot",
        "control_panel_title": "Bot-Kontrollpanel",
        "status_ready": "Status: Bereit",
        "status_running": "Status: Bot läuft",
        "status_stopped": "Status: Bot gestoppt",
        "start_button": "Bot Starten",
        "stop_button": "Bot Stoppen",
        "settings_button": "Einstellungen",
        "log_title": "Ereignisprotokoll",
        "dev_info": "Entwickelt von: FATİH / HKL | Version V1.10",
        "bot_start_log": "Söldner-Tausch-Bot-Aufgabe gestartet.",
        "folder_error": "Fehler: Bildordner '{}' nicht gefunden. Bitte den korrekten Pfad einstellen.",
        "folder_error_popup": "Bot konnte nicht gestartet werden. Bildordner '{}' nicht gefunden.",
        "tb_window_not_found": "Total Battle-Fenster nicht gefunden. Suche wird fortgesetzt...",
        "window_focus_error": "Fenster konnte nicht fokussiert werden: {}",
        "image_search_error": "Fehler bei der Bildersuche ({}): {}",
        "image_clicked_log": "Bild angeklickt: {} @ {}",
        "image_not_found_log": "Tauschbild nicht gefunden, Suche läuft weiter...",
        "bot_already_running_info": "Der Bot läuft bereits.",
        "bot_stopped_log": "Söldner-Bot wurde gestoppt.",
        "bot_already_stopped_info": "Der Bot ist bereits gestoppt.",
        "warning_popup_tb_window_not_found": "Total Battle-Fenster nicht gefunden. Bot läuft dennoch weiter, Zielgenauigkeit könnte eingeschränkt sein.",
        "exit_confirm": "Möchten Sie die Anwendung wirklich schließen? Der Bot wird gestoppt.",
        "settings_window_title": "Bot-Einstellungen",
        "confidence_label": "Bild-Erkennungsgenauigkeit (%):",
        "scan_time_label": "Scan-Wartezeit (Sekunden):",
        "focus_checkbox": "Total Battle-Fenster vor dem Klicken fokussieren",
        "sound_checkbox": "Tonbenachrichtigungen aktivieren",
        "tb_window_name_label": "Total Battle-Fenstername (ganz oder teilweise):",
        "choose_image_folder_button": "Bildordner auswählen",
        "image_folder_updated": "Bildordner aktualisiert: {}",
        "image_folder_cancelled": "Auswahl des Bildordners abgebrochen.",
        "choose_sound_file_button": "Audiodatei auswählen",
        "sound_file_updated": "Audiodatei aktualisiert: {}",
        "sound_file_cancelled": "Auswahl der Audiodatei abgebrochen.",
        "save_settings_button": "Einstellungen speichern",
        "settings_saved_log": "Einstellungen gespeichert:",
        "setting_confidence": "  Genauigkeit: {:.0f}%",
        "setting_scan_time": "  Scan-Geschwindigkeit: {:.1f} s",
        "setting_window_focus": "  Fenster-Fokus: {}",
        "setting_sound_enabled": "  Tonbenachrichtigung: {}",
        "setting_tb_window_name": "  TB-Fenstername: '{}'",
        "setting_image_folder": "  Bildordner: '{}'",
        "setting_sound_file": "  Audiodatei: '{}'",
        "setting_language": "  Gewählte Sprache: '{}'",
        "sound_error": "Ton konnte nicht abgespielt werden ({})",
        "sound_file_not_found": "Audiodatei nicht gefunden: {}",
        "language_select_label": "Sprachauswahl:",
        "language_updated": "Sprache aktualisiert: {}",
        "settings_not_saved_confirm": "Einstellungen wurden nicht gespeichert. Trotzdem schließen?",
        "settings_not_saved_title": "Nicht gespeicherte Einstellungen",
        "total_clicks_label": "Gesamte Klicks",
        "not_found_images_label": "Nicht gefundene Bilder",
        "last_trade_time_label": "Letzter Tauschzeitpunkt",
        "statistics_title": "Statistiken"
    }
}